function SaveAttitude(t, q1)
    [~, scenario] = GetCurrentRootAndScenario()
    
    sat = scenario.Children.Item("Satellite1");
    
    fileStr = strcat('stk.v.12.0\n\n', ...	
        '# WrittenBy    STK_v12.0.1\n\n', ...
        'BEGIN Attitude\n\n', ...
        sprintf('    NumberOfAttitudePoints		 %d', length(t)), ...
        '\n\n    BlockingFactor		 20\n\n', ...
        '    InterpolationOrder		 1\n\n', ...
        '    CentralBody		 Earth\n\n', ...
        '    ScenarioEpoch		 25 Jul 2021 16:00:00.000000\n\n', ...
        '    CoordinateAxes		 Fixed\n\n', ...
        '    AttitudeTimeQuaternions		\n');
    
    for i = 1:length(t)
        q = double(q1(i));
        fileStr = strcat(fileStr, ...
            sprintf("%e %e %e %e %e\n", t(i), q(2), q(3), q(4), q(1)));
    end
    fid = fopen('test.a','wt');
    fprintf(fid, fileStr);
    fclose(fid);

end

